### PR TITLE
enhancement: Regenerate code from latest protobufs

### PR DESCRIPTION
**Pull request by haines**
Pulls in changes to the plan resources types, including addition of validation errors.

### CODE REVIEW

**Review by charithe — APPROVED** [review]
LGTM

**Comment by haines** [comment]
@charithe I've suppressed the clippy lint that was breaking the build - could you please update the branch protection (it seems to be using an outdated workflow)?

**Comment by charithe** [comment]
Done. The auto-complete box on the UI shows a check that doesn't exist and lets me choose it 🤷🏽

**Comment by charithe** [comment]
@haines We should release this to crates.io, shouldn't we? I realised that I haven't setup a workflow for it. I will try to do that ASAP.

**Pull request merged**
